## **Cálculo Tensorial**

### Introducción:

Se utilizará la palabra tensor para hablar de tensores de segundo orden.  
Un tensor se puede presentar como una transformación lineal de un vector $\mathbf{T}(u)$

$\mathbf{T}:V\rightarrow V$ tal que para todo $ v \in V : v = \mathbf{T}(u) $

Si es una transformación lineal debe respetar los siguientes axiomas $\forall v,u\in V$ y $\forall \alpha\in \mathbb R$
- $T(u+v) = T(u)+T(v)$
- $T(\alpha v) = \alpha T(v)$

$T(v)$ también se puede escribir como $T\cdot v$, pero eso no indica producto interior ya que son de conjuntos diferentes.

Un tensor $\mathbf{T}$ se puede representar de acuerdo a una base donde $T_{ij}$ son los componentes del tensor con respecto a esa base y $\mathbf{e}_i \cdot (\mathbf{T}\cdot \mathbf{e}_j)= T_{ij}$  


#### El tensor con respecto a las bases se puede representar como:
  $\mathbf{T}= T_{ij}\mathbf{e}_i\mathbf{e}_j$


#### Matricialmente (3):  
Tensor $\mathbf{T} =
\begin{pmatrix}
\mathbf{e}_1 &\mathbf{e}_2 &\mathbf{e}_3\\
\end{pmatrix}  
\begin{pmatrix}
T_{11} & T_{12} & T_{13}\\
T_{21} & T_{22} & T_{23}\\
T_{31} & T_{32} & T_{33}\\
\end{pmatrix}
\begin{pmatrix}
\mathbf{e}_1 \\ \mathbf{e}_2 \\\mathbf{e}_3\\
\end{pmatrix}  $  


##### Simbólicamente
$\mathbf{T}=\mathbf{B}^T [T] \mathbf{B}$  
Donde $[T]$ es la matriz de componentes del tensor con respecto a la base $\mathbf{B}$

Para las bases cartesianas el tensor se representa solo como $[T]$, que es la forma utilizada aca:

## Utilizando 1D array para los vectores y 2D para los tensores

Vectores:  
$v = (2, 3, 5)$  $w=(1, 3, 6)$

In [120]:
import numpy as np
v=np.array([2,3,5])
w=np.array([1,3,6])
print("vector v: ",v)
print("vector w: ",w)

vector v:  [2 3 5]
vector w:  [1 3 6]


Tensor $T =
\begin{pmatrix}
1 & 2 & 3\\
4 & 1 & 9\\
8 & 6 & 7\\
\end{pmatrix}$

In [121]:
T=np.array([[1,2,3],[4,1,9],[8,6,7]])
print("tensor T: \n",T)

tensor T: 
 [[1 2 3]
 [4 1 9]
 [8 6 7]]


$\mathbf{T(v)}=
\begin{pmatrix}
1 & 2 & 3\\
4 & 1 & 9\\
8 & 6 & 7\\
\end{pmatrix}
\begin{pmatrix}
2\\
3\\
5\\
\end{pmatrix}=
\begin{pmatrix}
23\\
56\\
69\\
\end{pmatrix}$

In [122]:
T@v #No es necesario escribir el vector en 2D, np.dot da el mismo resultado, pero se recomienda @.

array([23, 56, 69])

Comprobando linealidad $T(v+w)=T(v)+T(w)$

In [123]:
T@(v+w)

array([ 48, 117, 137])

In [124]:
T@v+T@w #Mismo resultado

array([ 48, 117, 137])

Sea T un tensor y V un espacio vectorial: $T(V)=U$ es un subespacio de $V$ y la imagen de T.  
Por otro lado al subconjunto $W=(T(v)=0)$ se le denomina *núcleo* o *espacio nulo*.  
A la dimensión de U se le denomina *rango* de T  
A la dimensión de W se le denomina *nulidad* de T  
obviamente el *rango + nulidad* es igual a la dimensión de V


### Transpuesta de $T = T^T$

$\mathbf{T}=
\begin{pmatrix}
1 & 2 & 3\\
4 & 1 & 9\\
8 & 6 & 7\\
\end{pmatrix}
\mathbf{T}^T=
\begin{pmatrix}
1 & 4 & 8\\
2 & 1 & 6\\
3 & 9 & 7\\
\end{pmatrix}$

In [125]:
T.T #muy sencillo, esto solo tiene validéz en un tensor 2D.

array([[1, 4, 8],
       [2, 1, 6],
       [3, 9, 7]])

Comprobando que: $(T\cdot v)\cdot w = v\cdot(T^T\cdot w)$

In [126]:
(T@v)@w #utilizando el tensor T y los vectores v y w

605

In [127]:
v@(T.T@w) # y se comprueba la igualdad

605

### Parte simétrica y antisimétrica

Todo tensor puede dividirse en una parte simétrica y otra antisimétrica, siendo esta descomposición **única**  
$T=\frac{1}{2}(T+T^T)+\frac{1}{2}(T-T^T)$

$simétrica=
\begin{pmatrix}
a & d & e\\
d & b & f\\
e & f & c\\
\end{pmatrix}
antisimétrica=
\begin{pmatrix}
0 & -m & -n\\
m & 0 & -k\\
n & k & 0\\
\end{pmatrix}$

In [128]:
0.5*(T+T.T) #PArte simétrica

array([[1. , 3. , 5.5],
       [3. , 1. , 7.5],
       [5.5, 7.5, 7. ]])

In [129]:
0.5*(T-T.T) #Parte antisimétrica

array([[ 0. , -1. , -2.5],
       [ 1. ,  0. ,  1.5],
       [ 2.5, -1.5,  0. ]])

### Producto tensorial
$ vw=v\otimes w =
\begin{pmatrix}
2 & 6 & 12\\
3 & 9 & 18\\
5 & 15 & 30\\
\end{pmatrix}$

In [243]:
M=np.tensordot(v,w,axes=0) #axes=0 producto tensorial, axes=1 producto escalar, axes=2 doble producto interior para tensores
print(M)

[[ 2  6 12]
 [ 3  9 18]
 [ 5 15 30]]


Recordar que matricialmente el producto tensorial $v\otimes w= vw^T$ (donde los vectores se escriben en forma de columna)

Comprobando que $(u\otimes v)\cdot w = (v\cdot w)u$

ingresando el vector $u= (3,5,2)$

In [131]:
u=np.array([3,5,2])
print("vector u: ",u)

vector u:  [3 5 2]


In [244]:
np.tensordot(u,v,axes=0)@w #producto tensorial entre u y v y luego el producto con w

array([123, 205,  82])

In [133]:
(v@w)*u #Se comprueba que da el mismo resultado

array([123, 205,  82])

### Invariantes principales de un tensor

Para tensores son 3 escalares que NO dependen de la base, de ahí su nombre como invariantes.  
$I_1(\mathbf{T})$: traza de T, $I_2(\mathbf{T})$, $I_3(\mathbf{T})$: determinante de T,

#### Traza $tr(T)$
$T=
\begin{pmatrix}
1 & 2 & 3\\
4 & 1 & 9\\
8 & 6 & 7\\
\end{pmatrix}$
$tr(T) = 1+ 1+7=9$. (La suma de la diagonal)

In [134]:
np.trace(T)

9

#### Determinante  $det(T)$

In [135]:
np.linalg.det(T)

88.99999999999999

Si $det(T)=0$ existe un vector NO NULO n tal que $T\cdot n=0$  
Y por lo tanto la nulidad de T no es el espacio trivial {0}

#### Segundo invariante ($I_2$)

#### $I_2=\frac{1}{2}(T_{ii}T_{jj}-T_{ij}T_{ji})$ = $\frac{1}{2}[(tr\mathbf{T})^2-tr\mathbf{T}^2]$ =$\frac{1}{2}[(\mathbf{T:I})^2-\mathbf{T:T}]$

Para obtener directamente $I_2$ se escribirá como función:

In [136]:
def inv2(A): #función para el invariante dos utilizando la segunda definición
    if A.shape==(3,3):
        invariante2=0.5*(np.trace(A)**2-np.trace(A@A))
        return invariante2
    else:
        print("esta función es para tensores")

In [137]:
inv2(T)

-71.0

### Producto interior en Lin(V)
El espacio vectorial de los tensores Lin(V) tiene un producto interior:

$f(T,S) =tr(T^T\cdot S) = T:S$

$T=
\begin{pmatrix}
1 & 2 & 3\\
4 & 1 & 9\\
8 & 6 & 7\\
\end{pmatrix}$ 
$S=
\begin{pmatrix}
2 & 2 & 5\\
3 & 4 & 7\\
1 & 6 & 1\\
\end{pmatrix}$

In [138]:
S=np.array([[2,2,5],[3,4,7],[1,6,1]]) #ingresando S
print("tensor S: \n",S)

tensor S: 
 [[2 2 5]
 [3 4 7]
 [1 6 1]]


In [139]:
np.tensordot(T,S) #por defecto es axes=2 el doble producto interior

array(151)

In [245]:
print(T.T@S)
print("traza es: ",np.trace(T.T@S)) # mismo resultado por la definición

[[22 66 41]
 [13 44 23]
 [40 84 85]]
traza es:  151


In [141]:
np.sum(T*S) # lo mismo, se multiplican los elementos y luego se suman

151

#### Módulo de un tensor

Definido el producto interior, se puede obtener el módulo como la raiz de $T:T$

In [142]:
np.linalg.norm(T) #Obtenido directamente con la norma

16.15549442140351

In [143]:
np.tensordot(T,T)**0.5 #mismo resultado con la definición

16.15549442140351

### Tensores ortogonales

Un tensor Q es ortogonal si:   $Q^T\cdot Q = I$  
Estos tensores conservan el producto interior:  
$Q(v)\cdot Q(w)= v\cdot w$

Hay dos opciones:  
- $det(Q)= 1$ rotacional o tensor ortogonal propio
- $det(Q)= -1$ reflexión o tensor ortogonal impropio

Si R es rotación. El conjunto U={$v\in V: v = R\cdot v$} es un subespacio unidimencional de V conocido como eje de R.

Un tensor T es positivo definido si $v\cdot(T\cdot v)> 0$ (Si se agrega la igualdad es semi-positivo definido)

### Teorema Espectral

 #### $ \mathbf{T}\cdot \mathbf{e} = \alpha\cdot \mathbf{e}$
 Donde:  
 - $\mathbf{T}$: tensor cualquiera de Lin(V)
 - $\mathbf{e}$: vector unitario:  eigenvector, vector propio o vector característico.
 - $\alpha$ : escalar: eigenvalor, valor propio o valor característico asociado a $\mathbf{e}$

También se puede escribir como:  
#### $(\mathbf{T}-\alpha\mathbf{I})\cdot \mathbf{e}=0$  
Lo que se conoce como ecuación caracterítica de T que por definición también:
#### $\lambda^3-I_1\lambda^2+I_2\lambda-I_3=0$

Como los invariantes de T son reales, los valores propios son 3 o solo 1

- Todos los vectores $v$ tales que $T\cdot v= \lambda v$ forma el espacio característico de T, subespacio vectorial de V
- El espectro de T es la lista {$\lambda_1,\lambda_2,\lambda_3$}, donde: $\lambda_1\leq\lambda_2\leq\lambda_3$, los valores propios de T si es que existen.

SI un Tensor T es simétrico, entonces tiene 3 valores propios, y los espacios propios correspondientes a valores propios diferentes, son ortogonales.  
Así para un tensor simétrico existe al menos una base cartesiana compuesta solo por vectores propios, llamada base característica.

#### Descomposición espectral
Para un tensor simétrico Z, existe a lo menos una base característica y los valores propios asociados a ella forman el espectro total de Z

$Z =\displaystyle\sum_{i=3}^{3} \lambda_i\mathbf{e}_i$ 

Y Matricialmente:  
$\mathbf{B}^T
\begin{bmatrix}
\lambda_1 & 0 & 0\\
0 & \lambda_2 & 0\\
0 & 0 & \lambda_3\\
\end{bmatrix}\mathbf{B}$ 

- Si Z tiene 3 valores propios los espacios característicos son lineas mutuamente perpendiculares pasando por el origen
- Si Z tiene 2 valores propios se puede represenatr como $\lambda_1\mathbf{e}_1\mathbf{e}_1+\lambda_2(\mathbf{I}-\mathbf{e}_1\mathbf{e}_1)$ y los espacios característicos son $e_1$ y su ortogonal.
- SI Z tiene un solo valor propio se puede representar como $\lambda\mathbf{I}$ y V es el espacio característico

Ingresando tensor Z simétrico. 
$Z = \begin{pmatrix}
1 & 7 & 6\\
7 & 2 & 4\\
5 & 4 & 3\\
\end{pmatrix}$ 

In [144]:
Z=np.array([[1,7,6],[7,2,4],[5,4,3]])
print("tensor simétrico Z: \n", Z)

tensor simétrico Z: 
 [[1 7 6]
 [7 2 4]
 [5 4 3]]


##### Eigen-valores:
Se obtienen solo los eigenvalores con np.linalg.eigvals()  
Con np.diagflat se crea un 2D array que utiliza a otro array, en este caso 1D, como diagonal.

In [145]:
D=np.diagflat(np.linalg.eigvals(Z)) #con eigvals se obtiene un array 1D con los eigenvalores
# COn diagflat ese array pasa a ser la diagonal de un array 2D que se ha denominado D
print("Matriz de eigenvalores: \n", D) 

Matriz de eigenvalores: 
 [[13.          0.          0.        ]
 [ 0.         -5.79128785  0.        ]
 [ 0.          0.         -1.20871215]]


Esta nueva matriz compuesta por los eigenvalores, es igual a Z, pero con otra base (los eigenvectores), por lo que lo que posee los mismo invariantes ya que estos no dependen de la base.

##### $I_1$: Traza

In [146]:
print("traza de Z es: ",np.trace(Z), " y traza de D es:",np.trace(D)) # Se aprecia que son iguales

traza de Z es:  6  y traza de D es: 5.999999999999999


#### $I_2$  
Aplicando la función inv2 creada

In [148]:
print("segunda invariante de Z es: ",inv2(Z), " y de D es:",inv2(D)) # Se aprecia que son iguales

segunda invariante de Z es:  -84.0  y de D es: -83.99999999999993


##### $I_3$: Determinante

In [223]:
print("determinante de Z es: ",np.linalg.det(Z), " y determiante de D es:",np.linalg.det(D)) # Se aprecia que son iguales.

determinante de Z es:  90.99999999999997  y determiante de D es: 90.99999999999989


Comprobando la validez de los eigenvalores e invariantes de Z utilizando la ecuación característica:  
$\lambda^3-I_1\lambda^2+I_2\lambda-I_3=0$  
Con cualquier eigenvalor debería ser válida:

In [158]:
print(D[0,0]**3-np.trace(Z)*D[0,0]**2+inv2(Z)*D[0,0]-np.linalg.det(Z)) #utiliando los eigenvalores (diagonal de D)
print(D[1,1]**3-np.trace(Z)*D[1,1]**2+inv2(Z)*D[1,1]-np.linalg.det(Z))
print(D[2,2]**3-np.trace(Z)*D[2,2]**2+inv2(Z)*D[2,2]-np.linalg.det(Z))

-1.1084466677857563e-12
3.126388037344441e-13
7.105427357601002e-14


#### Eigen valores y Eigen vectores

In [224]:
val,vec=np.linalg.eig(Z) #Los eigen vectores están en cada columna correspondiente a cada eigen valor
print(val)
print(vec)

[13.         -5.79128785 -1.20871215]
[[-0.60899174 -0.77389339 -0.16152096]
 [-0.58307719  0.61237244 -0.61237244]
 [-0.53772675  0.16152096  0.77389339]]


Comprobando que $B^{-1}[T]B$ es igual a la matriz diagonal de los eigenvalores

In [225]:
np.linalg.inv(vec)@Z@vec

array([[ 1.30000000e+01,  3.33066907e-15,  8.88178420e-16],
       [ 6.21724894e-15, -5.79128785e+00,  0.00000000e+00],
       [ 2.88657986e-15,  7.21644966e-16, -1.20871215e+00]])

Comprobando la solución  
$Z = \begin{pmatrix}
1 & 7 & 6\\
7 & 2 & 4\\
5 & 4 & 3\\
\end{pmatrix}$ 

Primero se deben ordenar ya que el espectro es [$\lambda_1\leq\lambda_2\leq\lambda_3$]

In [206]:
D2=np.diagflat((np.linalg.eigvals(Z))[[1,2,0]])#también se puede usar roll
print(D2)

[[-5.79128785  0.          0.        ]
 [ 0.         -1.20871215  0.        ]
 [ 0.          0.         13.        ]]


Ahora se reordena los vectores

In [216]:
vec2=np.roll(vec,-1,axis=1)#Se reordena, solo fue necesario usar roll -1 (0,1,2) a (1,2,0)
print(vec2)

[[-0.77389339 -0.16152096 -0.60899174]
 [ 0.61237244 -0.61237244 -0.58307719]
 [ 0.16152096  0.77389339 -0.53772675]]
