## Cálculo vectorial

#### Ingresando dos vectores
 $v = (2,3,4)$\
 $w = (1,3,5)$

In [2]:
import numpy as np

In [3]:
v = np.array([2,3,4])
w = np.array([1,3,5])

 ### Suma de vectores

In [4]:
v + w #simplemente sumando

array([3, 6, 9])

In [5]:
np.add(v,w) #Lo mismo pero escribiendo la función

array([3, 6, 9])

### Multiplicación por escalar

In [6]:
3*v #multiplicando al vector

array([ 6,  9, 12])

In [7]:
np.multiply(3,v) #escribiendo la función

array([ 6,  9, 12])

### Producto escalar

In [8]:
np.dot(v,w) #Escribiendo la función, esta se recomienda solo para vectores, es decir 1D.

31

In [9]:
v@w #utilizando @, ésta forma se recomienda en matrices, es decir 2D

31

### Producto vectorial

In [10]:
np.cross(v,w) #producto vectorial

array([ 3, -6,  3])

### Producto tensorial

In [11]:
np.tensordot(v,w,axes=0) #Generalziando axes=0 producto tensorial, 1 = producto punto, 2= doble producto punto(tensores)

array([[ 2,  6, 10],
       [ 3,  9, 15],
       [ 4, 12, 20]])

### Norma
En vectores se utiliza np.linalg.norm(vector, norma).

$\lVert v \rVert_n = (\sum \lvert v_i\rvert^n)^{1/n}$

In [24]:
from cmath import inf

np.linalg.norm(v,inf) #norma infinito es igual al mayor valor

4.0

In [23]:
np.dot(v,v)**(1/2) #la norma 2 es igual a la norma por producto interior

5.385164807134504